init article django
Zerofiltre-Courses/articles pull request #1
Opened 2023-03-11 09:07 UTC by arolleaguekeng

2023-03-11 09:08 UTC, arolleaguekeng commented
django article init

2023-03-12 11:59 UTC, imphilippesimo requested changes
1/Tous les fichiers non nécessaires doivent être supprimés. Nous ne tenons que à garder les fichiers sources python. Donc il faut supprimer .idea/ les fichier pyc, 

2/ Après avoir supprimé, rajoute un fichier .giignore afin que ce type de fichiers ne remontent plus.

3/ Utilise ce gitignore 
https://www.toptal.com/developers/gitignore/api/python,django

2023-03-12 12:49 UTC, arolleaguekeng commented
Bien reçu

Le dim. 12 mars 2023 à 13:00, Philippe SIMO GUEMKAM <
***@***.***> a écrit :

> ***@***.**** requested changes on this pull request.
>
> 1/Tous les fichiers non nécessaires doivent être supprimés. Nous ne tenons
> que à garder les fichiers sources python. Donc il faut supprimer .idea/ les
> fichier pyc,
>
> 2/ Après avoir supprimé, rajoute un fichier .giignore afin que ce type de
> fichiers ne remontent plus.
>
> 3/ Utilise ce gitignore
> https://www.toptal.com/developers/gitignore/api/python,django
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zerofiltre-Courses/articles/pull/1#pullrequestreview-1336011892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWIF4UZXAVA6PQWVD3NM43DW3W3EJANCNFSM6AAAAAAVXL3ULQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-12 18:31 UTC, imphilippesimo approved these changes
Il y'a un dossier _pycache dans le dossier migrations mais c'est pas grave. Je vais accepter la pull request.

2023-03-12 18:31 UTC, merged

2023-03-12 19:25 UTC, arolleaguekeng commented
D'accord.
C'est quoi la suite svp ?

Le dim. 12 mars 2023 à 19:31, Philippe SIMO GUEMKAM <
***@***.***> a écrit :

> ***@***.**** approved this pull request.
>
> Il y'a un dossier _pycache dans le dossier migrations mais c'est pas
> grave. Je vais accepter la pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zerofiltre-Courses/articles/pull/1#pullrequestreview-1336067072>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWIF4U6H2J2FNNW6TOJ5UJTW3YJA7ANCNFSM6AAAAAAVXL3ULQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-12 20:08 UTC, imphilippesimo commented
Numéro OM

Paiement

On Sun, Mar 12, 2023, 20:25 AGUEKENG Arolle Dubois ***@***.***>
wrote:

> D'accord.
> C'est quoi la suite svp ?
>
> Le dim. 12 mars 2023 à 19:31, Philippe SIMO GUEMKAM <
> ***@***.***> a écrit :
>
> > ***@***.**** approved this pull request.
> >
> > Il y'a un dossier _pycache dans le dossier migrations mais c'est pas
> > grave. Je vais accepter la pull request.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/Zerofiltre-Courses/articles/pull/1#pullrequestreview-1336067072
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AWIF4U6H2J2FNNW6TOJ5UJTW3YJA7ANCNFSM6AAAAAAVXL3ULQ
> >
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Zerofiltre-Courses/articles/pull/1#issuecomment-1465279265>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADI6EHU3C5NOVBJCUTKAPITW3YPKJANCNFSM6AAAAAAVXL3ULQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>